### ISSUE TITLE
Conversion to RNC returns a zip file

### ISSUE THREAD

**Issue by raffazizzi** [TEIC/TEIGarage#81] opened 2024-05-14 13:37 UTC
Converting an ODD file to RNG Compact (RNC) syntax currently returns a zip file containing and RNG file and and a converted RNC file. I think it would be helpful to just return a plain text rnc file, or at least add a parameter to request it as such.

**Comment by anneferger** [comment] 2024-06-04 15:18
I confirmed that this is exactly the same issue as the last time some years ago - and it doesn't happen on the dev version at https://teigarage.tei-c.de (which is the same version as the main version currently), so this is again because a temp file is not deleted successfully. I will fix this in the backend and not the setup this time though, so it can't reappear again.

**Comment by peterstadler** [comment] 2024-06-05 12:17
PR #85 addresses this and has been merged

**Comment by anneferger** [comment] 2024-06-06 15:31
Sorry need to reopen this one, it works on our test setup but not the original setup, will try another option

**Comment by anneferger** [comment] 2024-06-07 06:59
Now it is actually fixed in https://github.com/TEIC/tei-converter/commit/2aca34e60bf65ce01776d0606871d3f232032b91 and updated in https://teigarage.tei-c.org/. Thanks for tracking this bug again!

**Closed by anneferger** 2024-06-07 06:59 UTC
